import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Inline the pdf.worker as a text plugin so it can be used as a Blob URL at runtime
const workerPlugin = {
  name: "pdf-worker-inline",
  setup(build) {
    build.onResolve({ filter: /pdf\.worker/ }, () => ({
      path: require.resolve("pdfjs-dist/legacy/build/pdf.worker.min.js"),
      namespace: "pdf-worker",
    }));
    build.onLoad({ filter: /.*/, namespace: "pdf-worker" }, (args) => ({
      contents: `module.exports = ${JSON.stringify(fs.readFileSync(args.path, "utf8"))};`,
      loader: "js",
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  plugins: [workerPlugin],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
